### ISSUE TITLE
About COCO-CN datasets

### ISSUE THREAD

**Issue by kobeshegu** [bingwork/ChartPDF#1]
Hi, bingwork,

Sorry to bother you. I'm a Ph.D student from East China University of Science and Technology, I noticed that you once provied a repo for downloading the COCO-CN dataset. However, it is now unavailable. I have filled out the Google form for requesting the dataset but got no response. So I wonder if you could send me the download code, I admit that all data will only used for research, my eamils are kobeshegu@gmail.com or mengpingyang@mail.ecust.edu.cn. Thanks a lot for you kind help.
Thanks again.
Best regards,
Mengping.

**Comment by bingwork** [comment]
Hi @kobeshegu, I suggest accessing the dataset from https://huggingface.co/datasets/MMInstruction/M3IT if you need it. You can find the coco-cn dataset within this extensive dataset. However, it is recommended to send an email to Professor Li, as mentioned in the reference link https://github.com/li-xirong/coco-cn, to obtain more information.

**Comment by kobeshegu** [comment]
Thanks :)
